import styles from "./index.module.css";
import { type NextPage } from "next";
import  Image  from "next/image";
import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";

const CreatePostsWizard = () => {
  const { user } = useUser();

  if(!user) return null;

  return <div>
    <img src={user.profileImageUrl} width={50} height={50} />
    <input placeholder="Type something" />
  </div>
}

const Home: NextPage = () => {
  const user = useUser();
  
  const { data, isLoading } = api.posts.getAll.useQuery();
  console.log(data);

  if(isLoading) return <div>Loading...</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && (<div><CreatePostsWizard/><SignOutButton/></div>)}
        </div>
        <div>
          {data?.map((post) => (<div key={post.id}>{post.content}</div>))}
        </div>
      </main>
    </>
  );
};

export default Home;